### ISSUE TITLE
Remove bootstrap tags

### ISSUE THREAD

**Issue by david-kroell** [david-kroell/ytdl#14]
@abhilakshyadobhal introduced with #8 a new userinterface design.
Unfortunately, there are still the old bootstrap HTML tags remaining in the index.html file.
It's time to clear the old bootstrap tags up, to make it more lightweigth and maintainable.

**Comment by abhilakshyadobhal** [comment]
ok i will surely remove those unwanted bootstrap classes as without those classes it is responsive.
