### ISSUE TITLE
Statistical analysis

### ISSUE THREAD

**Issue by david-kroell** [david-kroell/ytdl#20]
Create SQL queries (MySQL preferred) for statistical analysis. A file (download_stats.sql) is placed in this repos root directory. You can use this to set up your database table and fill it with example data.

Aggregate this data and show me some statistics which would be nice to print out on a webpage diagram.

For example: Top 10 Downloaded videos within last seven days.

**Comment by flaredragon** [comment]
Hey I've worked on some stats should i create a seperate file?

**Comment by flaredragon** [comment]
Hey I've worked on some stats would like your feedback on them.
