### ISSUE TITLE
Frontend: redesign whole view

### ISSUE THREAD

**Issue by david-kroell** [david-kroell/ytdl#3]
Try to redesign the whole UI.
Make use of frontend libraries other than bootstrap (or use a theme). Or use your own stylesheets without a library.
Different versions welcomed

**Comment by disisisid** [comment]
I can take this.

**Comment by david-kroell** [comment]
That's fine!
Which framework are you going to use?

**Comment by disisisid** [comment]
I think I can write some styles.

**Comment by david-kroell** [comment]
@disisisid if you are still working on this, just submit a pull request.
If not, tell me

**Comment by disisisid** [comment]
I haven't got around to this. I see this has been solved.

**Comment by david-kroell** [comment]
Ok, I'm closing this issue.
